# Generated by Django 5.2.6 on 2025-11-16 11:52

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251116_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'ادمین', 'verbose_name_plural': 'ادمین ها'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش ها'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='cantact_phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_admins', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='work_phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='شماره کاری'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='نام نمایشی'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(verbose_name='سطوح دسترسی'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='average_monthly_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='میانگین فروش ماهانه'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(max_length=100, validators=[utils.validators.validate_bank_account], verbose_name='حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cantact_phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='verified_at',
            field=models.DateTimeField(null=True, verbose_name='تایید شده در'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_seller', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='work_phone',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='شماره کاری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(null=True, verbose_name='آدرس آواتار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[utils.validators.validate_phone_number], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.role', verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
