# Generated by Django 5.2.6 on 2025-11-26 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_options_alter_admin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='ایجاد شده در'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='reciever_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='reciever_phone',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
