# Generated by Django 5.2.6 on 2025-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_created_at_address_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
