# Generated by Django 5.2.6 on 2025-12-27 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_city_alter_address_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_admins', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
    ]
