# Generated by Django 5.2.6 on 2025-12-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='cantact_phone',
            new_name='contact_phone',
        ),
    ]
