# Generated by Django 5.2.6 on 2025-11-16 08:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20251116_0911'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأییدشده'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت\u200cنشده'), ('paid', 'پرداخت\u200cشده'), ('refunded', 'بازپرداخت\u200cشده'), ('failed', 'ناموفق')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مشتری')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان به\u200cروزرسانی')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.discount', verbose_name='تخفیف')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.address', verbose_name='آدرس حمل\u200cونقل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('product_snapshot', models.JSONField(blank=True, null=True, verbose_name='تصویر محصول')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت واحد')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('payment_method', models.CharField(max_length=50, verbose_name='روش پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق'), ('refunded', 'بازپرداخت\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway_response', models.TextField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه بازپرداخت')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ بازپرداخت')),
                ('card_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='شماره کارت (مخفی)')),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پرداخت\u200cکننده')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بازپرداخت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان به\u200cروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره پیگیری')),
                ('courier', models.CharField(blank=True, max_length=100, null=True, verbose_name='پیک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('picked_up', 'برداشته\u200cشده'), ('in_transit', 'در حال حمل'), ('delivered', 'تحویل\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('shipping_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای حمل\u200cونقل')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('delivered_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحویل به')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان به\u200cروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'حمل\u200cونقل',
                'verbose_name_plural': 'حمل\u200cونقل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان استفاده')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.discount', verbose_name='تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'indexes': [models.Index(fields=['user'], name='orders_disc_user_id_299c60_idx'), models.Index(fields=['used_at'], name='orders_disc_used_at_741641_idx')],
                'constraints': [models.UniqueConstraint(fields=('discount', 'order'), name='unique_discount_order')],
            },
        ),
    ]
