# Generated by Django 5.2.6 on 2025-11-17 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("discount_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "درصد"),
                            ("fixed", "ثابت"),
                            ("free_shipping", "حمل و نقل رایگان"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "min_purchase",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("max_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("usage_limit_total", models.PositiveIntegerField(null=True)),
                ("usage_limit_per_user", models.PositiveIntegerField(null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("percentage", "درصد"),
                            ("fixed", "ثابت"),
                            ("free_shipping", "حمل و نقل رایگان"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("traget_ids", models.JSONField(default=list)),
                ("first_purchase_only", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField()),
                ("icon_url", models.URLField()),
                ("banner_url", models.URLField(blank=True, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "parent_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("CHECKED OUT", "پرداخت شده"),
                            ("EXPIRED", "منقضی شده"),
                        ],
                        default="ACTIVE",
                        max_length=11,
                    ),
                ),
                ("items", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discount_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.discount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight_kg", models.DecimalField(decimal_places=3, max_digits=8)),
                ("dimensions", models.CharField(max_length=50)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "category_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "product_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField()),
                ("alt_text", models.CharField(max_length=255)),
                ("position", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
