# Generated by Django 5.2.6 on 2025-11-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='discount_id',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='discount_id',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_id', to='products.category'),
        ),
    ]
