# Generated by Django 5.2.6 on 2025-12-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_type_discount_discount_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='traget_ids',
            new_name='target_ids',
        ),
    ]
