# Generated by Django 5.2.6 on 2025-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_traget_ids_discount_target_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(choices=[('all', 'همه'), ('products', 'محصولات'), ('categories', 'دسته بندی ها')], default='all', max_length=20),
        ),
    ]
